import { Item } from "@/interface/Item";
export const items: Item[] = [
  {
    id: 1,
    name: "나이키 반팔티",
    image: "nk.jpg",
    amount: 25000,
  },
  {
    id: 2,
    name: "아디다스 운동화",
    image: "ad.jpg",
    amount: 27900,
    discount: 10,
  },
  {
    id: 3,
    name: "뉴발란스 조거팬츠",
    image: "nb.jpg",
    amount: 32000,
  },
  {
    id: 4,
    name: "리복 후드티",
    image: "rb.jpg",
    amount: 40000,
    discount: 15,
  },
  {
    id: 5,
    name: "언더아머 반바지",
    image: "ua.webp",
    amount: 23000,
  },
  {
    id: 6,
    name: "푸마 스니커즈",
    image: "pm.jpg",
    amount: 29000,
    discount: 5,
  },
  {
    id: 7,
    name: "스파오 맨투맨",
    image: "sp.jpg",
    amount: 18000,
  },
  {
    id: 8,
    name: "자라 데님 자켓",
    image: "jr.webp",
    amount: 45000,
    discount: 20,
  },
  {
    id: 9,
    name: "코스 오버사이즈 티셔츠",
    image: "cs.jpeg",
    amount: 35000,
  },
  {
    id: 10,
    name: "H&M 슬랙스",
    image: "hm.jpeg",
    amount: 27000,
    discount: 10,
  },
  {
    id: 11,
    name: "유니클로 경량 패딩",
    image: "un.jpg",
    amount: 59000,
    discount: 25,
  },
  {
    id: 12,
    name: "올젠 셔츠",
    image: "oj.jpeg",
    amount: 38000,
  },
  {
    id: 13,
    name: "탑텐 니트",
    image: "tt.jpeg",
    amount: 32000,
  },
  {
    id: 14,
    name: "지오다노 청바지",
    image: "jdn.webp",
    amount: 42000,
    discount: 5,
  },
  {
    id: 15,
    name: "라코스테 폴로티",
    image: "rcs.jpg",
    amount: 49000,
    discount: 15,
  },
  {
    id: 16,
    name: "빈폴 패딩",
    image: "bp.webp",
    amount: 120000,
    discount: 20,
  },
  {
    id: 17,
    name: "에잇세컨즈 셔츠",
    image: "eight.jpg",
    amount: 27000,
  },
  {
    id: 18,
    name: "폴햄 후드집업",
    image: "ph.jpg",
    amount: 38000,
    discount: 10,
  },
  {
    id: 19,
    name: "페라가모 벨트",
    image: "pg.jpg",
    amount: 89000,
    discount: 5,
  },
  {
    id: 20,
    name: "루이비통 지갑",
    image: "rvt.jpeg",
    amount: 350000,
    discount: 30,
  },
];
